# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Contacto.create(nombre:'Fernando',telefono:'123456789',email:'a@a.com')
Contacto.create(nombre:'Bertha',telefono:'123456789',email:'a@a.com')
Contacto.create(nombre:'Yamile',telefono:'123456789',email:'a@a.com')
Usuario.create(nombre:'pepe',email:'p@p.com',url_imagen:'http://res.cloudinary.com/hqrpaoswi/image/upload/v1542627750/User-Icon-Default.png')
Usuario.create(nombre:'pepito',email:'p@p.com',url_imagen:'http://res.cloudinary.com/hqrpaoswi/image/upload/v1542627750/User-Icon-Default.png')
Usuario.create(nombre:'pepa',email:'p@p.com',url_imagen:'http://res.cloudinary.com/hqrpaoswi/image/upload/v1542627750/User-Icon-Default.png')
Humedal.create(nombre:'Jaboque',direccion:'Calle 1234',ubicacion:'4.6516342,-74.0711358,15',descripcion:'El Humedal Jaboque se ubica en la localidad de Engativá, hace parte de la cuenca del río Salitre, un sistema hídrico de gran importancia conformado por siete canales, de los cuales Los Ángeles, El Carmelo y Marantá confluyen en el área protegida.El Humedal Jaboque ha sido reconocido por la presencia de monolitos prehispánicos, que lo convierten en uno de los humedales de mayor interés arqueológico. Cuenta con un observatorio astronómico, monolitos que dispusieron nuestros antepasados Muiscas en cercanía al Río Bogotá. Al igual que otros pueblos indígenas de América, mediante la fijación de puntos de observación en los monolitos los muiscas del Jaboque determinaron las fechas para la siembra y la cosecha, pero teniendo en cuenta que la sabana permanecía inundada, dieron especial importancia a la determinación del comienzo de las épocas secas, en donde podían cultivar productos un poco más resistentes como la papa o el maíz .',horario_atencion:'8:00 am - 4:00 pm',contacto_id:1)
Humedal.create(nombre:'Jaboque 1',direccion:'Calle 1234',ubicacion:'4.6516342,-74.0711358,15',descripcion:'El Humedal Jaboque se ubica en la localidad de Engativá, hace parte de la cuenca del río Salitre, un sistema hídrico de gran importancia conformado por siete canales, de los cuales Los Ángeles, El Carmelo y Marantá confluyen en el área protegida.El Humedal Jaboque ha sido reconocido por la presencia de monolitos prehispánicos, que lo convierten en uno de los humedales de mayor interés arqueológico. Cuenta con un observatorio astronómico, monolitos que dispusieron nuestros antepasados Muiscas en cercanía al Río Bogotá. Al igual que otros pueblos indígenas de América, mediante la fijación de puntos de observación en los monolitos los muiscas del Jaboque determinaron las fechas para la siembra y la cosecha, pero teniendo en cuenta que la sabana permanecía inundada, dieron especial importancia a la determinación del comienzo de las épocas secas, en donde podían cultivar productos un poco más resistentes como la papa o el maíz .',horario_atencion:'8:00 am - 4:00 pm',contacto_id:2)
Humedal.create(nombre:'Jaboque 2',direccion:'Calle 1234',ubicacion:'4.6516342,-74.0711358,15',descripcion:'El Humedal Jaboque se ubica en la localidad de Engativá, hace parte de la cuenca del río Salitre, un sistema hídrico de gran importancia conformado por siete canales, de los cuales Los Ángeles, El Carmelo y Marantá confluyen en el área protegida.El Humedal Jaboque ha sido reconocido por la presencia de monolitos prehispánicos, que lo convierten en uno de los humedales de mayor interés arqueológico. Cuenta con un observatorio astronómico, monolitos que dispusieron nuestros antepasados Muiscas en cercanía al Río Bogotá. Al igual que otros pueblos indígenas de América, mediante la fijación de puntos de observación en los monolitos los muiscas del Jaboque determinaron las fechas para la siembra y la cosecha, pero teniendo en cuenta que la sabana permanecía inundada, dieron especial importancia a la determinación del comienzo de las épocas secas, en donde podían cultivar productos un poco más resistentes como la papa o el maíz .',horario_atencion:'8:00 am - 4:00 pm',contacto_id:3)
Denuncia.create(observaciones:'Hay desechos en el humedal',estado:'activo',usuarios_id:1,humedals_id:1)
Denuncia.create(observaciones:'Hay desechos',estado:'activo',usuarios_id:1,humedals_id:1)
Denuncia.create(observaciones:'Hay basuras',estado:'activo',usuarios_id:2,humedals_id:2)
FotosHumedal.create(url_imagen:'https://res.cloudinary.com/hqrpaoswi/image/upload/v1542627636/samples/landscapes/nature-mountains.jpg',esPrincipal:false,humedal_id:1)
FotosHumedal.create(url_imagen:'https://res.cloudinary.com/hqrpaoswi/image/upload/v1542627633/samples/landscapes/beach-boat.jpg',esPrincipal:true,humedal_id:1)
FotosHumedal.create(url_imagen:'https://res.cloudinary.com/hqrpaoswi/video/upload/v1542627639/samples/sea-turtle.mp4',esPrincipal:false,humedal_id:1)
SuscripcionesHumedal.create(usuario_id:1,humedal_id:1)
SuscripcionesHumedal.create(usuario_id:1,humedal_id:2)
SuscripcionesHumedal.create(usuario_id:2,humedal_id:1)
Evento.create(descripcion:"Capacitacion sobre los humedals y sus problematicas",url_imagen:'https://res.cloudinary.com/hqrpaoswi/image/upload/v1542627636/samples/cloudinary-group.jpg',organizador:'Huemdales Bogota',horario:'31 de Noviembre 2018 08:00 a.m',contacto_id:1,humedal_id:1)
Evento.create(descripcion:"Capacitacion sobre los humedals y sus problematicas",url_imagen:'https://res.cloudinary.com/hqrpaoswi/image/upload/v1542627630/samples/bike.jpg',organizador:'Huemdales Bogota',horario:'31 de Noviembre 2018 08:00 a.m',contacto_id:1,humedal_id:2)
Evento.create(descripcion:"Capacitacion sobre los humedals y sus problematicas",url_imagen:'https://res.cloudinary.com/hqrpaoswi/image/upload/v1542627636/samples/cloudinary-group.jpg',organizador:'Huemdales Bogota',horario:'31 de Noviembre 2018 08:00 a.m',contacto_id:2,humedal_id:3)
